using D2NG.Core.D2GS.Items;
using Serilog;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace D2NG.Core.DataManager;

internal class ItemPropertyDataType
{
    public List<ItemPropertyEntry> ItemProperties { get; }

    public Dictionary<StatType, ItemPropertyEntry> ItemPropertiesByStatType { get; }

    public ItemPropertyDataType(string file)
    {
        var propertiesMap = GetItemPropertiesMap();
        ItemProperties = [];
        ItemPropertiesByStatType = [];

        List<string> lines = [];

        using (StreamReader r = new(file))
        {
            string line;
            while ((line = r.ReadLine()) != null)
            {
                lines.Add(line);
            }
        }

        foreach (string line in lines)
        {
            try
            {
                String[] tokens = line.Split('|');
                if (tokens.Length == 0)
                {
                    continue;
                }

                if (tokens.Length != 4)
                {
                    Log.Error($"Invalid Token Count: {tokens.Length} on line {line}");
                }

                string name = tokens[0];
                int saveBits = int.Parse(tokens[1]);
                int saveParamBits = int.Parse(tokens[2]);
                int saveAdd = int.Parse(tokens[3]);
                var statType = name == "Unused" ? propertiesMap[name + " " + saveBits] : propertiesMap[name];
                var i = new ItemPropertyEntry(name, statType, saveBits, saveParamBits, saveAdd);
                ItemProperties.Add(i);
                ItemPropertiesByStatType.TryAdd(i.StatType, i);
            }
            catch (Exception e)
            {
                Log.Error("Error parsing ItemPropertyEntry: {0}", e.ToString());
            }
        }
    }

    public ItemPropertyEntry Get(int propertyId)
    {
        return ItemProperties.ElementAtOrDefault(propertyId);
    }

    public ItemPropertyEntry GetByStatType(StatType statType)
    {
        return ItemPropertiesByStatType.GetValueOrDefault(statType);
    }

    private static Dictionary<string, StatType> GetItemPropertiesMap()
    {
        Dictionary<string, StatType> propertiesNameToTypeMap = new()
        {
            ["Strength"] = StatType.Strength,
            ["Energy"] = StatType.Energy,
            ["Dexterity"] = StatType.Dexterity,
            ["Vitality"] = StatType.Vitality,
            ["All Attributes"] = StatType.AllAttributes,
            ["New Skills1"] = StatType.NewSkills1,
            ["New Skills2"] = StatType.NewSkills2,
            ["Life"] = StatType.Life,
            ["Maximum Life"] = StatType.MaximumLife,
            ["Mana"] = StatType.Mana,
            ["Maximum Mana"] = StatType.MaximumMana,
            ["Maximum Stamina"] = StatType.MaximumStamina,
            ["Level"] = StatType.Level,
            ["Experience"] = StatType.Experience,
            ["Gold"] = StatType.Gold,
            ["Bank"] = StatType.Bank,
            ["Enhanced Defense"] = StatType.EnhancedDefense,
            ["Enhanced Maximum Damage"] = StatType.EnhancedMaximumDamage,
            ["Enhanced Minimum Damage"] = StatType.EnhancedMinimumDamage,
            ["Attack Rating"] = StatType.AttackRating,
            ["Increased Blocking"] = StatType.IncreasedBlocking,
            ["Minimum Damage"] = StatType.MinimumDamage,
            ["Maximum Damage"] = StatType.MaximumDamage,
            ["Secondary Minimum Damage"] = StatType.SecondaryMinimumDamage,
            ["Secondary Maximum Damage"] = StatType.SecondaryMaximumDamage,
            ["Enhanced Damage"] = StatType.EnhancedDamage,
            ["Mana Recovery"] = StatType.ManaRecovery,
            ["Mana Recovery Bonus"] = StatType.ManaRecoveryBonus,
            ["Stamina Recovery Bonus"] = StatType.StaminaRecoveryBonus,
            ["Last Experience"] = StatType.LastExperience,
            ["Next Experience"] = StatType.NextExperience,
            ["Defense"] = StatType.Defense,
            ["Defense vs. Missiles"] = StatType.DefenseVsMissiles,
            ["Defense vs. Melee"] = StatType.DefenseVsMelee,
            ["Damage Reduction"] = StatType.DamageReduction,
            ["Magical Damage Reduction"] = StatType.MagicalDamageReduction,
            ["Damage Reduction (Percent)"] = StatType.DamageReductionPercent,
            ["Magical Damage Reduction (Percent)"] = StatType.MagicalDamageReductionPercent,
            ["Maximum Magical Damage Reduction (Percent)"] = StatType.MaximumMagicalDamageReductionPercent,
            ["Fire Resistance"] = StatType.FireResistance,
            ["Maximum Fire Resistance"] = StatType.MaximumFireResistance,
            ["Lightning Resistance"] = StatType.LightningResistance,
            ["Maximum Lightning Resistance"] = StatType.MaximumLightningResistance,
            ["Cold Resistance"] = StatType.ColdResistance,
            ["Maximum Cold Resistance"] = StatType.MaximumColdResistance,
            ["Poison Resistance"] = StatType.PoisonResistance,
            ["Maximum Poison Resistance"] = StatType.MaximumPoisonResistance,
            ["Damage Aura"] = StatType.DamageAura,
            ["Minimum Fire Damage"] = StatType.MinimumFireDamage,
            ["Maximum Fire Damage"] = StatType.MaximumFireDamage,
            ["Minimum Lightning Damage"] = StatType.MinimumLightningDamage,
            ["Maximum Lightning Damage"] = StatType.MaximumLightningDamage,
            ["Minimum Magical Damage"] = StatType.MinimumMagicalDamage,
            ["Maximum Magical Damage"] = StatType.MaximumMagicalDamage,
            ["Minimum Cold Damage"] = StatType.MinimumColdDamage,
            ["Maximum Cold Damage"] = StatType.MaximumColdDamage,
            ["Cold Damage Length"] = StatType.ColdDamageLength,
            ["Minimum Poison Damage"] = StatType.MinimumPoisonDamage,
            ["Maximum Poison Damage"] = StatType.MaximumPoisonDamage,
            ["Poison Damage length"] = StatType.PoisonDamageLength,
            ["Minimum Life Stolen Per Hit"] = StatType.MinimumLifeStolenPerHit,
            ["Maximum Life Stolen Per Hit"] = StatType.MaximumLifeStolenPerHit,
            ["Minimum Mana Stolen Per Hit"] = StatType.MinimumManaStolenPerHit,
            ["Maximum Mana Stolen Per Hit"] = StatType.MaximumManaStolenPerHit,
            ["Minimum Stamina Drain"] = StatType.MinimumStaminaDrain,
            ["Maximum Stamina Drain"] = StatType.MaximumStaminaDrain,
            ["Stun Length"] = StatType.StunLength,
            ["Velocity Percent"] = StatType.VelocityPercent,
            ["Attack Rate"] = StatType.AttackRate,
            ["Other Animation Rate"] = StatType.OtherAnimationRate,
            ["Quantity"] = StatType.Quantity,
            ["Value"] = StatType.Value,
            ["Durability"] = StatType.Durability,
            ["Maximum Durability"] = StatType.MaximumDurability,
            ["Replenish Life"] = StatType.ReplenishLife,
            ["Enhanced Maximum Durability"] = StatType.EnhancedMaximumDurability,
            ["Enhanced Life"] = StatType.EnhancedLife,
            ["Enhanced Mana"] = StatType.EnhancedMana,
            ["Attacker Takes Damage"] = StatType.AttackerTakesDamage,
            ["Extra Gold"] = StatType.ExtraGold,
            ["Better Chance Of Getting Magic Item"] = StatType.BetterChanceOfGettingMagicItem,
            ["Knockback"] = StatType.Knockback,
            ["Time Duration"] = StatType.TimeDuration,
            ["Amazon Skills"] = StatType.AmazonSkills,
            ["Paladin Skills"] = StatType.PaladinSkills,
            ["Necromancer Skills"] = StatType.NecromancerSkills,
            ["Sorceress Skills"] = StatType.SorceressSkills,
            ["Barbarian Skills"] = StatType.BarbarianSkills,
            ["Unsent Parameter"] = StatType.UnsentParameter,
            ["Add Experience"] = StatType.AddExperience,
            ["Life After Each Kill"] = StatType.LifeAfterEachKill,
            ["Reduce Vendor Prices"] = StatType.ReduceVendorPrices,
            ["Double Herb Duration"] = StatType.DoubleHerbDuration,
            ["Light Radius"] = StatType.LightRadius,
            ["Light Colour"] = StatType.LightColour,
            ["Reduced Requirements"] = StatType.ReducedRequirements,
            ["Reduced Level Requirement"] = StatType.ReducedLevelRequirement,
            ["Increased Attack Speed"] = StatType.IncreasedAttackSpeed,
            ["Reduced Level Requirement (Percent)"] = StatType.ReducedLevelRequirementPercent,
            ["Last Block Frame"] = StatType.LastBlockFrame,
            ["Faster Run Walk"] = StatType.FasterRunWalk,
            ["Non Class Skill"] = StatType.NonClassSkill,
            ["State"] = StatType.State,
            ["Faster Hit Recovery"] = StatType.FasterHitRecovery,
            ["Monster Player Count"] = StatType.MonsterPlayerCount,
            ["Skill Poison Override Length"] = StatType.SkillPoisonOverrideLength,
            ["Faster Block Rate"] = StatType.FasterBlockRate,
            ["Skill Bypass Undead"] = StatType.SkillBypassUndead,
            ["Skill Bypass Demons"] = StatType.SkillBypassDemons,
            ["Faster Cast Rate"] = StatType.FasterCastRate,
            ["Skill Bypass Beasts"] = StatType.SkillBypassBeasts,
            ["Single Skill1"] = StatType.SingleSkill1,
            ["Single Skill2"] = StatType.SingleSkill2,
            ["Single Skill3"] = StatType.SingleSkill3,
            ["Poison Length Reduction"] = StatType.PoisonLengthReduction,
            ["Adds Damage"] = StatType.AddsDamage,
            ["Hit Causes Monster To Flee"] = StatType.HitCausesMonsterToFlee,
            ["Hit Blinds Target"] = StatType.HitBlindsTarget,
            ["Damage To Mana"] = StatType.DamageToMana,
            ["Ignore Target's Defense"] = StatType.IgnoreTargetsDefense,
            ["Reduce Target's Defense"] = StatType.ReduceTargetsDefense,
            ["Prevent Monster Heal"] = StatType.PreventMonsterHeal,
            ["Half Freeze Duration"] = StatType.HalfFreezeDuration,
            ["To Hit Percent"] = StatType.ToHitPercent,
            ["Monster Defense Reduction per Hit"] = StatType.MonsterDefenseReductionPerHit,
            ["Damage To Demons"] = StatType.DamageToDemons,
            ["Damage To Undead"] = StatType.DamageToUndead,
            ["Attack Rating Against Demons"] = StatType.AttackRatingAgainstDemons,
            ["Attack Rating Against Undead"] = StatType.AttackRatingAgainstUndead,
            ["Throwable"] = StatType.Throwable,
            ["Fire Skills"] = StatType.FireSkills,
            ["All Skills"] = StatType.AllSkills,
            ["Attacker Takes Lightning Damage"] = StatType.AttackerTakesLightningDamage,
            ["Iron Maiden Level"] = StatType.IronMaidenLevel,
            ["Lifetap Level"] = StatType.LifetapLevel,
            ["Thorns Percent"] = StatType.ThornsPercent,
            ["Bone Armor"] = StatType.BoneArmor,
            ["Maximum Bone Armor"] = StatType.MaximumBoneArmor,
            ["Freezes Target"] = StatType.FreezesTarget,
            ["Open Wounds"] = StatType.OpenWounds,
            ["Crushing Blow"] = StatType.CrushingBlow,
            ["Kick Damage"] = StatType.KickDamage,
            ["Mana After Each Kill"] = StatType.ManaAfterEachKill,
            ["Life After Each Demon Kill"] = StatType.LifeAfterEachDemonKill,
            ["Extra Blood"] = StatType.ExtraBlood,
            ["Deadly Strike"] = StatType.DeadlyStrike,
            ["Fire Absorption (Percent)"] = StatType.FireAbsorptionPercent,
            ["Fire Absorption"] = StatType.FireAbsorption,
            ["Lightning Absorption (Percent)"] = StatType.LightningAbsorptionPercent,
            ["Lightning Absorption"] = StatType.LightningAbsorption,
            ["Magic Absorption (Percent)"] = StatType.MagicAbsorptionPercent,
            ["Magic Absorption"] = StatType.MagicAbsorption,
            ["Cold Absorption (Percent)"] = StatType.ColdAbsorptionPercent,
            ["Cold Absorption"] = StatType.ColdAbsorption,
            ["Slows Down Enemies"] = StatType.SlowsDownEnemies,
            ["Aura"] = StatType.Aura,
            ["Indestructible"] = StatType.Indestructible,
            ["Cannot Be Frozen"] = StatType.CannotBeFrozen,
            ["Stamina Drain (Percent)"] = StatType.StaminaDrainPercent,
            ["Reanimate"] = StatType.Reanimate,
            ["Piercing Attack"] = StatType.PiercingAttack,
            ["Fires Magic Arrows"] = StatType.FiresMagicArrows,
            ["Fire Explosive Arrows"] = StatType.FireExplosiveArrows,
            ["Minimum Throwing Damage"] = StatType.MinimumThrowingDamage,
            ["Maximum Throwing Damage"] = StatType.MaximumThrowingDamage,
            ["Skill Hand Of Athena"] = StatType.SkillHandOfAthena,
            ["Skill Stamina (Percent)"] = StatType.SkillStaminaPercent,
            ["Skill Passive Stamina (Percent)"] = StatType.SkillPassiveStaminaPercent,
            ["Concentration"] = StatType.Concentration,
            ["Enchant"] = StatType.Enchant,
            ["Pierce"] = StatType.Pierce,
            ["Conviction"] = StatType.Conviction,
            ["Chilling Armor"] = StatType.ChillingArmor,
            ["Frenzy"] = StatType.Frenzy,
            ["Decrepify"] = StatType.Decrepify,
            ["Skill Armor Percent"] = StatType.SkillArmorPercent,
            ["Alignment"] = StatType.Alignment,
            ["Target 0"] = StatType.Target0,
            ["Target 1"] = StatType.Target1,
            ["Gold Lost"] = StatType.GoldLost,
            ["Conversion Level"] = StatType.ConversionLevel,
            ["Conversion Maximum Life"] = StatType.ConversionMaximumLife,
            ["Unit Do Overlay"] = StatType.UnitDoOverlay,
            ["Druid Skills"] = StatType.DruidSkills,
            ["Assassin Skills"] = StatType.AssassinSkills,
            ["Single Skill4"] = StatType.SingleSkill4,
            ["Armor Override Percent"] = StatType.ArmorOverridePercent,
            ["Unused 183"] = StatType.Unused183,
            ["Unused 184"] = StatType.Unused184,
            ["Unused 185"] = StatType.Unused185,
            ["Unused 186"] = StatType.Unused186,
            ["Unused 187"] = StatType.Unused187,
            ["Skill Tab1"] = StatType.SkillTab1,
            ["Skill Tab2"] = StatType.SkillTab2,
            ["Skill Tab3"] = StatType.SkillTab3,
            ["Skill Tab4"] = StatType.SkillTab4,
            ["Skill Tab5"] = StatType.SkillTab5,
            ["Skill Tab6"] = StatType.SkillTab6,
            ["Socket Count"] = StatType.SocketCount,
            ["Skill On Striking"] = StatType.SkillOnStriking,
            ["Skill On Kill"] = StatType.SkillOnKill,
            ["Skill On Death"] = StatType.SkillOnDeath,
            ["Skill On Hit"] = StatType.SkillOnHit,
            ["Skill On Level Up"] = StatType.SkillOnLevelUp,
            ["Unused 200"] = StatType.Unused200,
            ["Skill When Struck1"] = StatType.SkillWhenStruck1,
            ["Skill When Struck2"] = StatType.SkillWhenStruck2,
            ["Skill When Struck3"] = StatType.SkillWhenStruck3,
            ["Charged"] = StatType.Charged,
            ["Unused 204"] = StatType.Unused204,
            ["Unused 205"] = StatType.Unused205,
            ["Unused 206"] = StatType.Unused206,
            ["Unused 207"] = StatType.Unused207,
            ["Unused 208"] = StatType.Unused208,
            ["Unused 209"] = StatType.Unused209,
            ["Unused 210"] = StatType.Unused210,
            ["Unused 211"] = StatType.Unused211,
            ["Unused 212"] = StatType.Unused212,
            ["Defense Per Level"] = StatType.DefensePerLevel,
            ["Enhanced Defense Per Level"] = StatType.EnhancedDefensePerLevel,
            ["Life Per Level"] = StatType.LifePerLevel,
            ["Mana Per Level"] = StatType.ManaPerLevel,
            ["Maximum Damage Per Level"] = StatType.MaximumDamagePerLevel,
            ["Maximum Enhanced Damage Per Level"] = StatType.MaximumEnhancedDamagePerLevel,
            ["Strength Per Level"] = StatType.StrengthPerLevel,
            ["Dexterity Per Level"] = StatType.DexterityPerLevel,
            ["Energy Per Level"] = StatType.EnergyPerLevel,
            ["Vitality Per Level"] = StatType.VitalityPerLevel,
            ["Attack Rating Per Level"] = StatType.AttackRatingPerLevel,
            ["Bonus To Attack Rating Per Level"] = StatType.BonusToAttackRatingPerLevel,
            ["Maximum Cold Damage Per Level"] = StatType.MaximumColdDamagePerLevel,
            ["Maximum Fire Damage Per Level"] = StatType.MaximumFireDamagePerLevel,
            ["Maximum Lightning Damage Per Level"] = StatType.MaximumLightningDamagePerLevel,
            ["Maximum Poison Damage Per Level"] = StatType.MaximumPoisonDamagePerLevel,
            ["Cold Resistance Per Level"] = StatType.ColdResistancePerLevel,
            ["Fire Resistance Per Level"] = StatType.FireResistancePerLevel,
            ["Lightning Resistance Per Level"] = StatType.LightningResistancePerLevel,
            ["Poison Resistance Per Level"] = StatType.PoisonResistancePerLevel,
            ["Cold Absorption Per Level"] = StatType.ColdAbsorptionPerLevel,
            ["Fire Absorption Per Level"] = StatType.FireAbsorptionPerLevel,
            ["Lightning Absorption Per Level"] = StatType.LightningAbsorptionPerLevel,
            ["Poison Absorption Per Level"] = StatType.PoisonAbsorptionPerLevel,
            ["Thorns Per Level"] = StatType.ThornsPerLevel,
            ["Extra Gold Per Level"] = StatType.ExtraGoldPerLevel,
            ["Better Chance Of Getting Magic Item Per Level"] = StatType.BetterChanceOfGettingMagicItemPerLevel,
            ["Stamina Regeneration Per Level"] = StatType.StaminaRegenerationPerLevel,
            ["Stamina Per Level"] = StatType.StaminaPerLevel,
            ["Damage To Demons Per Level"] = StatType.DamageToDemonsPerLevel,
            ["Damage To Undead Per Level"] = StatType.DamageToUndeadPerLevel,
            ["Attack Rating Against Demons Per Level"] = StatType.AttackRatingAgainstDemonsPerLevel,
            ["Attack Rating Against Undead Per Level"] = StatType.AttackRatingAgainstUndeadPerLevel,
            ["Crushing Blow Per Level"] = StatType.CrushingBlowPerLevel,
            ["Open Wounds Per Level"] = StatType.OpenWoundsPerLevel,
            ["Kick Damage Per Level"] = StatType.KickDamagePerLevel,
            ["Deadly Strike Per Level"] = StatType.DeadlyStrikePerLevel,
            ["Find Gems Per Level"] = StatType.FindGemsPerLevel,
            ["Repairs Durability"] = StatType.RepairsDurability,
            ["Replenishes Quantity"] = StatType.ReplenishesQuantity,
            ["Increased Stack Size"] = StatType.IncreasedStackSize,
            ["Find Item"] = StatType.FindItem,
            ["Slash Damage"] = StatType.SlashDamage,
            ["Slash Damage (Percent)"] = StatType.SlashDamagePercent,
            ["Crush Damage"] = StatType.CrushDamage,
            ["Crush Damage (Percent)"] = StatType.CrushDamagePercent,
            ["Thrust Damage"] = StatType.ThrustDamage,
            ["Thrust Damage (Percent)"] = StatType.ThrustDamagePercent,
            ["Slash Damage Absorption"] = StatType.SlashDamageAbsorption,
            ["Crush Damage Absorption"] = StatType.CrushDamageAbsorption,
            ["Thrust Damage Absorption"] = StatType.ThrustDamageAbsorption,
            ["Slash Damage Absorption (Percent)"] = StatType.SlashDamageAbsorptionPercent,
            ["Crush Damage Absorption (Percent)"] = StatType.CrushDamageAbsorptionPercent,
            ["Thrust Damage Absorption (Percent)"] = StatType.ThrustDamageAbsorptionPercent,
            ["Defense Per Time"] = StatType.DefensePerTime,
            ["Enhanced Defense Per Time"] = StatType.EnhancedDefensePerTime,
            ["Life Per Time"] = StatType.LifePerTime,
            ["Mana Per Time"] = StatType.ManaPerTime,
            ["Maximum Damage Per Time"] = StatType.MaximumDamagePerTime,
            ["Maximum Enhanced Damage Per Time"] = StatType.MaximumEnhancedDamagePerTime,
            ["Strength Per Time"] = StatType.StrengthPerTime,
            ["Dexterity Per Time"] = StatType.DexterityPerTime,
            ["Energy Per Time"] = StatType.EnergyPerTime,
            ["Vitality Per Time"] = StatType.VitalityPerTime,
            ["Attack Rating Per Time"] = StatType.AttackRatingPerTime,
            ["Chance To Hit Per Time"] = StatType.ChanceToHitPerTime,
            ["Maximum Cold Damage Per Time"] = StatType.MaximumColdDamagePerTime,
            ["Maximum Fire Damage Per Time"] = StatType.MaximumFireDamagePerTime,
            ["Maximum Lightning Damage Per Time"] = StatType.MaximumLightningDamagePerTime,
            ["Maximum Damage Per Poison"] = StatType.MaximumDamagePerPoison,
            ["Cold Resistance Per Time"] = StatType.ColdResistancePerTime,
            ["Fire Resistance Per Time"] = StatType.FireResistancePerTime,
            ["Lightning Resistance Per Time"] = StatType.LightningResistancePerTime,
            ["Poison Resistance Per Time"] = StatType.PoisonResistancePerTime,
            ["Cold Absorption Per Time"] = StatType.ColdAbsorptionPerTime,
            ["Fire Absorption Per Time"] = StatType.FireAbsorptionPerTime,
            ["Lightning Absorption Per Time"] = StatType.LightningAbsorptionPerTime,
            ["Poison Absorption Per Time"] = StatType.PoisonAbsorptionPerTime,
            ["Extra Gold Per Time"] = StatType.ExtraGoldPerTime,
            ["Better Chance Of Getting Magic Item Per Time"] = StatType.BetterChanceOfGettingMagicItemPerTime,
            ["Regenerate Stamina Per Time"] = StatType.RegenerateStaminaPerTime,
            ["Stamina Per Time"] = StatType.StaminaPerTime,
            ["Damage To Demons Per Time"] = StatType.DamageToDemonsPerTime,
            ["Damage To Undead Per Time"] = StatType.DamageToUndeadPerTime,
            ["Attack Rating Against Demons Per Time"] = StatType.AttackRatingAgainstDemonsPerTime,
            ["Attack Rating Against Undead Per Time"] = StatType.AttackRatingAgainstUndeadPerTime,
            ["Crushing Blow Per Time"] = StatType.CrushingBlowPerTime,
            ["Open Wounds Per Time"] = StatType.OpenWoundsPerTime,
            ["Kick Damage Per Time"] = StatType.KickDamagePerTime,
            ["Deadly Strike Per Time"] = StatType.DeadlyStrikePerTime,
            ["Find Gems Per Time"] = StatType.FindGemsPerTime,
            ["Enemy Cold Resistance Reduction"] = StatType.EnemyColdResistanceReduction,
            ["Enemy Fire Resistance Reduction"] = StatType.EnemyFireResistanceReduction,
            ["Enemy Lightning Resistance Reduction"] = StatType.EnemyLightningResistanceReduction,
            ["Enemy Poison Resistance Reduction"] = StatType.EnemyPoisonResistanceReduction,
            ["Damage vs. Monsters"] = StatType.DamageVsMonsters,
            ["Enhanced Damage vs. Monsters"] = StatType.EnhancedDamageVsMonsters,
            ["Attack Rating Against Monsters"] = StatType.AttackRatingAgainstMonsters,
            ["Bonus To Attack Rating Against Monsters"] = StatType.BonusToAttackRatingAgainstMonsters,
            ["Defense vs. Monsters"] = StatType.DefenseVsMonsters,
            ["Enhanced Defense vs. Monsters"] = StatType.EnhancedDefenseVsMonsters,
            ["Fire Damage Length"] = StatType.FireDamageLength,
            ["Minimum Fire Damage Length"] = StatType.MinimumFireDamageLength,
            ["Maximum Fire Damage Length"] = StatType.MaximumFireDamageLength,
            ["Progressive Damage"] = StatType.ProgressiveDamage,
            ["Progressive Steal"] = StatType.ProgressiveSteal,
            ["Progressive Other"] = StatType.ProgressiveOther,
            ["Progressive Fire"] = StatType.ProgressiveFire,
            ["Progressive Cold"] = StatType.ProgressiveCold,
            ["Progressive Lightning"] = StatType.ProgressiveLightning,
            ["Extra Charges"] = StatType.ExtraCharges,
            ["Progressive Attack Rating"] = StatType.ProgressiveAttackRating,
            ["Poison Count"] = StatType.PoisonCount,
            ["Damage Framerate"] = StatType.DamageFramerate,
            ["Pierce IDX"] = StatType.PierceIdx,
            ["Fire Mastery"] = StatType.FireMastery,
            ["Lightning Mastery"] = StatType.LightningMastery,
            ["Cold Mastery"] = StatType.ColdMastery,
            ["Poison Mastery"] = StatType.PoisonMastery,
            ["Passive Enemy Fire Resistance Reduction"] = StatType.PassiveEnemyFireResistanceReduction,
            ["Passive Enemy Lightning Resistance Reduction"] = StatType.PassiveEnemyLightningResistanceReduction,
            ["Passive Enemy Cold Resistance Reduction"] = StatType.PassiveEnemyColdResistanceReduction,
            ["Passive Enemy Poison Resistance Reduction"] = StatType.PassiveEnemyPoisonResistanceReduction,
            ["Critical Strike"] = StatType.CriticalStrike,
            ["Dodge"] = StatType.Dodge,
            ["Avoid"] = StatType.Avoid,
            ["Evade"] = StatType.Evade,
            ["Warmth"] = StatType.Warmth,
            ["Melee Attack Rating Mastery"] = StatType.MeleeAttackRatingMastery,
            ["Melee Damage Mastery"] = StatType.MeleeDamageMastery,
            ["Melee Critical Hit Mastery"] = StatType.MeleeCriticalHitMastery,
            ["Thrown Weapon Attack Rating Mastery"] = StatType.ThrownWeaponAttackRatingMastery,
            ["Thrown Weapon Damage Mastery"] = StatType.ThrownWeaponDamageMastery,
            ["Thrown Weapon Critical Hit Mastery"] = StatType.ThrownWeaponCriticalHitMastery,
            ["Weapon Block"] = StatType.WeaponBlock,
            ["Summon Resist"] = StatType.SummonResist,
            ["Modifier List Skill"] = StatType.ModifierListSkill,
            ["Modifier List Level"] = StatType.ModifierListLevel,
            ["Last Sent Life Percent"] = StatType.LastSentLifePercent,
            ["Source Unit Type"] = StatType.SourceUnitType,
            ["Source Unit ID"] = StatType.SourceUnitId,
            ["Short Parameter 1"] = StatType.ShortParameter1,
            ["Quest Item Difficulty"] = StatType.QuestItemDifficulty,
            ["Passive Magical Damage Mastery"] = StatType.PassiveMagicalDamageMastery,
            ["Passive Magical Resistance Reduction"] = StatType.PassiveMagicalResistanceReduction
        };
        return propertiesNameToTypeMap;
    }
}
