<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Marten" Version="9.29.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.11" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="MudBlazor" Version="9.8.0" />
    <PackageVersion Include="RoyT.AStar" Version="3.0.2" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="SharpPcap" Version="6.3.1" />
    <PackageVersion Include="SharpZipLib" Version="1.4.2" />
    <PackageVersion Include="Stateless" Version="5.20.1" />
    <PackageVersion Include="Telegram.Bot" Version="22.10.2.1" />
    <PackageVersion Include="Telegram.Bot.Extensions.Polling" Version="1.0.2" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>