version: 2
jobs:
  checkout_code:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/project
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: dotnet build
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1  }}
          paths:
            - ~/project
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: dotnet test

workflows:
  version: 2
  build-test-and-docker:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build
