using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace D2NG.Core.ItemData;

public enum AffixQuality
{
    Magic,

    /// <summary>Rare and crafted items draw from the same affixes: those flagged <see cref="AffixEntry.Rare"/>.</summary>
    Rare
}

/// <summary>
/// The affixes, item types, bases and cube recipes of the game's compiled tables, for answering
/// what can actually spawn on an item. Generated by the MpqData tool; nothing loads it at runtime yet.
/// </summary>
public sealed class ItemAffixTable
{
    private Dictionary<string, ItemTypeEntry> _typesByCode;

    public List<ItemAffixSourceFile> Sources { get; set; } = [];
    public List<ItemTypeEntry> ItemTypes { get; set; } = [];
    public List<BaseItemEntry> BaseItems { get; set; } = [];
    public List<AffixEntry> Affixes { get; set; } = [];
    public List<CubeRecipeEntry> CubeRecipes { get; set; } = [];

    public static ItemAffixTable Load(string path)
        => JsonSerializer.Deserialize<ItemAffixTable>(File.ReadAllText(path), SerializerOptions);

    public void Save(string path) => File.WriteAllText(path, JsonSerializer.Serialize(this, SerializerOptions));

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter() }
    };

    /// <summary>Whether <paramref name="type"/> is <paramref name="ancestor"/> or descends from it.</summary>
    public bool IsA(string type, string ancestor)
    {
        _typesByCode ??= ItemTypes.Where(t => !string.IsNullOrEmpty(t.Code)).GroupBy(t => t.Code).ToDictionary(g => g.Key, g => g.First());
        var seen = new HashSet<string>();
        var pending = new Stack<string>();
        pending.Push(type);
        while (pending.Count > 0)
        {
            var current = pending.Pop();
            if (current == ancestor)
            {
                return true;
            }

            if (current == null || !seen.Add(current) || !_typesByCode.TryGetValue(current, out var entry))
            {
                continue;
            }

            pending.Push(entry.Equivalent1);
            pending.Push(entry.Equivalent2);
        }

        return false;
    }

    public bool IsA(BaseItemEntry item, string ancestor)
        => IsA(item.Type, ancestor) || (item.Type2 != null && IsA(item.Type2, ancestor));

    /// <summary>
    /// The prefixes and suffixes that can roll on <paramref name="item"/>, following the game's own
    /// filter: spawnable, a non-zero frequency, the version gate, the rare flag for rare and crafted
    /// items, and the item type lists with exclusions winning. Item level is left to the caller, as
    /// each affix carries its own level window. Class-specific affixes are included; they only stay
    /// off items that belong to a different class.
    /// </summary>
    public IEnumerable<AffixEntry> EligibleAffixes(BaseItemEntry item, bool expansion, AffixQuality quality)
        => Affixes.Where(affix =>
            affix.Kind != AffixKind.AutoMagic
            && affix.Spawnable
            && affix.Frequency > 0
            && affix.Mods.Count > 0
            && (expansion || !affix.IsExpansionOnly)
            && (quality == AffixQuality.Magic || affix.Rare)
            && !affix.ExcludedItemTypes.Any(type => IsA(item, type))
            && affix.ItemTypes.Any(type => IsA(item, type)));
}

/// <summary>Provenance of one compiled table, so a stale extract can be told from a fresh one.</summary>
public sealed class ItemAffixSourceFile
{
    public string File { get; set; }
    public string Archive { get; set; }
    public string Sha256 { get; set; }
    public int RecordCount { get; set; }
    public int RecordSize { get; set; }
    public DateTime ExtractedUtc { get; set; }
}
