<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MpqDumpApp</RootNamespace>
    <AssemblyName>MpqDump</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\D2NG.Core\D2NG.Core.csproj" />
  </ItemGroup>

</Project>
