namespace D2NG.D2GS.Objects
{
    public enum Waypoint : byte
    {
        RogueEncampment = 0x01,
        ColdPlains = 0x03,
        StonyFields = 0x04,
        DarkWood = 0x05,
        BlackMarsh = 0x06,
        OuterCloister = 0x1B,
        JailLevel1 = 0x1D,
        InnerCloister = 0x20,
        CatacombsLevel2 = 0x23,
        LutGholein = 0x28,
        SewersLevel2 = 0x30,
        DryHills = 0x2A,
        HallsOfTheDeadLevel2 = 0x39,
        FarOasis = 0x2B,
        LostCity = 0x2C,
        PalaceCellarLevel1 = 0x34,
        ArcaneSanctuary = 0x4A,
        CanyonOfTheMagi = 0x2E,
        KurastDocks = 0x4B,
        SpiderForest = 0x4C,
        GreatMarsh = 0x4D,
        FlayerJungle = 0x4E,
        LowerKurast = 0x4F,
        KurastBazaar = 0x50,
        UpperKurast = 0x51,
        Travincal = 0x53,
        DuranceOfHateLevel2 = 0x65,
        ThePandemoniumFortress = 0x67,
        CityOfTheDamned = 0x6A,
        RiverOfFlame = 0x6B,
        Harrogath = 0x6D,
        FrigidHighlands = 0x6F,
        ArreatPlateau = 0x70,
        CrystallinePassage = 0x71,
        GlacialTrail = 0x73,
        HallsOfPain = 0x7B,
        FrozenTundra = 0x75,
        TheAncientsWay = 0x76,
        TheWorldStoneKeepLevel2 = 0x81
    }
}
