using D2NG.Core.ItemData;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace MpqData;

/// <summary>
/// Writes what can spawn on each item type as markdown, one file per game type, for reviewing nip
/// rules against: a rule asking for more than the best affix can roll never matches, and a rule
/// asking a classic item for an expansion-only stat is dead.
/// </summary>
internal static class AffixReport
{
    public static void Write(ItemAffixTable table, string directory)
    {
        Directory.CreateDirectory(directory);
        foreach (var expansion in new[] { false, true })
        {
            var path = Path.Combine(directory, expansion ? "affixes-expansion.md" : "affixes-classic.md");
            File.WriteAllText(path, Build(table, expansion));
            Console.WriteLine($"  wrote {path}");
        }
    }

    private static string Build(ItemAffixTable table, bool expansion)
    {
        var game = expansion ? "Expansion" : "Classic";
        var text = new StringBuilder();
        text.AppendLine($"# What can spawn on magic, rare and crafted items - {game}");
        text.AppendLine();
        text.AppendLine("Generated by `tools/MpqData --report` from the compiled tables the game loads:");
        text.AppendLine();
        foreach (var source in table.Sources)
        {
            text.AppendLine($"- `{source.File}` from {source.Archive}, {source.RecordCount} records, sha256 {source.Sha256[..12]}");
        }

        text.AppendLine();
        text.AppendLine("How to read it:");
        text.AppendLine();
        text.AppendLine("- An affix rolls when the item level reaches its `lvl` and does not pass its `max lvl`.");
        text.AppendLine("- Magic items get at most one prefix and one suffix. Rare and crafted items only draw from the");
        text.AppendLine("  affixes marked rare, and never two of one group, so the stat ranges are per affix: the same");
        text.AppendLine("  property can still stack when a prefix and a suffix both carry it.");
        if (!expansion)
        {
            text.AppendLine("- Classic games only roll affixes and bases below version 100, and have no crafting.");
        }
        else
        {
            text.AppendLine("- `exp` marks affixes that only roll in expansion games.");
        }

        text.AppendLine("- Property codes are the game's own (properties.bin); a skill-on-event property reads");
        text.AppendLine("  `code(skill) chance-level`.");
        text.AppendLine();

        var groups = table.BaseItems
            .Where(item => item.Type != null && (expansion || !item.IsExpansionOnly))
            .GroupBy(item => (item.Type, item.Type2))
            .OrderBy(group => group.First().Kind)
            .ThenBy(group => group.Key.Type);

        foreach (var group in groups)
        {
            var sample = group.First();
            var type = table.ItemTypes.FirstOrDefault(t => t.Code == sample.Type);
            if (type == null || type.AlwaysNormal)
            {
                continue;
            }

            var magic = table.EligibleAffixes(sample, expansion, AffixQuality.Magic).ToList();
            if (magic.Count == 0)
            {
                continue;
            }

            var rare = type.CanBeRare ? table.EligibleAffixes(sample, expansion, AffixQuality.Rare).ToHashSet() : [];
            var typeName = sample.Type2 != null ? $"{sample.Type} / {sample.Type2}" : sample.Type;
            text.AppendLine($"## {typeName}");
            text.AppendLine();
            text.AppendLine("Bases: " + string.Join(", ", group.Select(item => $"{item.Name} (`{item.Code}`, q{item.Level})")));
            text.AppendLine();
            text.AppendLine($"Rare: {(type.CanBeRare ? "yes" : "no")}. Max sockets: {type.MaxSockets}." +
                (type.StaffMods != null ? $" Staff mods: {type.StaffMods}." : ""));
            text.AppendLine();

            text.AppendLine("| property | magic | best magic affix | rare/crafted | best rare affix |");
            text.AppendLine("|---|---|---|---|---|");
            foreach (var row in StatRanges(magic, rare))
            {
                text.AppendLine($"| {row.Property} | {row.Magic} | {row.MagicBest} | {row.Rare} | {row.RareBest} |");
            }

            text.AppendLine();
            text.AppendLine("<details><summary>Every affix</summary>");
            text.AppendLine();
            text.AppendLine("| | affix | mods | lvl | max lvl | req | freq | group | rare | class |");
            text.AppendLine("|---|---|---|---|---|---|---|---|---|---|");
            foreach (var affix in magic.OrderBy(a => a.Kind).ThenBy(a => a.Group).ThenBy(a => a.Level))
            {
                var kind = affix.Kind == AffixKind.Prefix ? "P" : "S";
                var name = affix.Name + (expansion && affix.IsExpansionOnly ? " *exp*" : "");
                var mods = string.Join(", ", affix.Mods);
                var maxLevel = affix.MaxLevel == 0 ? "" : affix.MaxLevel.ToString();
                text.AppendLine($"| {kind} | {name} | {mods} | {affix.Level} | {maxLevel} | {affix.LevelRequirement} | {affix.Frequency} | {affix.Group} | {(rare.Contains(affix) ? "yes" : "")} | {affix.ClassSpecific} |");
            }

            text.AppendLine();
            text.AppendLine("</details>");
            text.AppendLine();
        }

        if (expansion)
        {
            AppendCrafting(table, text);
        }

        return text.ToString();
    }

    private static void AppendCrafting(ItemAffixTable table, StringBuilder text)
    {
        var crafts = table.CubeRecipes.Where(recipe => recipe.Enabled && recipe.IsCraft).ToList();
        text.AppendLine("## Crafted recipes");
        text.AppendLine();
        text.AppendLine("Each output keeps the fixed mods below and then rolls affixes like a rare item of its base.");
        text.AppendLine("`plvl/ilvl` is how the output's item level splits between the player's level and the input's.");
        text.AppendLine();
        text.AppendLine("| # | inputs | fixed mods | plvl/ilvl |");
        text.AppendLine("|---|---|---|---|");
        foreach (var recipe in crafts)
        {
            text.AppendLine($"| {recipe.Index} | {string.Join(" + ", recipe.Inputs)} | {string.Join(", ", recipe.Mods)} | {recipe.PlayerLevelPercent}/{recipe.ItemLevelPercent} |");
        }

        text.AppendLine();
    }

    private sealed record StatRow(string Property, string Magic, string MagicBest, string Rare, string RareBest);

    private static IEnumerable<StatRow> StatRanges(List<AffixEntry> magic, HashSet<AffixEntry> rare)
    {
        var mods = magic
            .SelectMany(affix => affix.Mods.Select(mod => (Affix: affix, Mod: mod)))
            .GroupBy(entry => entry.Mod.Param != 0 ? $"{entry.Mod.Property}({entry.Mod.Param})" : entry.Mod.Property)
            .OrderBy(group => group.Key);

        foreach (var group in mods)
        {
            var all = group.ToList();
            var rares = all.Where(entry => rare.Contains(entry.Affix)).ToList();
            yield return new StatRow(group.Key, Range(all), Best(all), Range(rares), Best(rares));
        }
    }

    private static string Range(List<(AffixEntry Affix, PropertyRange Mod)> entries)
        => entries.Count == 0 ? "-" : $"{entries.Min(e => e.Mod.Min)}-{entries.Max(e => e.Mod.Max)}";

    private static string Best(List<(AffixEntry Affix, PropertyRange Mod)> entries)
    {
        if (entries.Count == 0)
        {
            return "";
        }

        var best = entries.OrderByDescending(e => e.Mod.Max).ThenBy(e => e.Affix.Level).First();
        return $"{best.Affix.Name} lvl {best.Affix.Level}";
    }
}
