<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="D2NG.Core.D2GS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConsoleBot\ConsoleBot.csproj" />
    <ProjectReference Include="..\D2NG.Core\D2NG.Core.csproj" />
  </ItemGroup>

</Project>
