name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Add source
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/dkuwahara/index.json" -UserName dkuwahara -Password GH_TOKEN 
    - name: Pack
      run: nuget pack
    - name: Push Artifact
      run: nuget push "D2NG.nupkg" -Source "GitHub"
      
